### ISSUE TITLE
Exception upon opening: Attempted to read or write protected memory

### ISSUE THREAD

**Issue by Eagle3386** [otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET#9] opened 2020-09-23 09:58 UTC
Repro steps:
1. Download non-ZIP-DLL version from https://forums.getpaint.net/topic/117086-scalable-vector-graphics-filetype-alternative-plugin-svg-svgz/.
2. Move to C:\Program Files\Paint.NET\FileTypes.
3. Restart PDN (if open prior to plugin installation).
4. Open [Fx-Browser-Developer-icon-fullColor.svg](https://github.com/otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET/files/5267173/Fx-Browser-Developer-icon-fullColor.zip) (note: GH doesn't support SVG uploads, hence inside ZIP).
5. Set <kbd>Canvas</kbd> (2nd group box) to 4096 x 4096.
6. Click <kbd>Groups (Unstable)</kbd> or <kbd>All Layers</kbd> (3rd group box)
7. Click <kbd>OK</kbd>

Error: 
> Attempted to read or write protected memory. This is often an indication that other memory is corrupted.
> ![image](https://user-images.githubusercontent.com/5111490/93997893-2b337080-fd94-11ea-8045-a4bd47d458a5.png)

Note 1: Memory modules were tested, all of them are fine.
Note 2: Yes, it does say `Unstable` within the `Layers` group box and the file itself seems to contain only 1 layer.
But IMHO, neither an error nor even an exception should occur upon no further groups or layers.

Further diagnostics:
```
Exception:

System.OperationCanceledException: Cancelled by user
   at SvgFileTypePlugin.SvgFileType.Get(Stream input)
   at PaintDotNet.FileType.Load(Stream input) in D:\src\pdn\src\Data\FileType.cs:line 513
   at PaintDotNet.Functional.Func.Eval[T1,TRet](Func`2 f, T1 arg1) in D:\src\pdn\src\Base\Functional\Func.cs:line 158

Diagnostics:

Application                                          paint.net 4.2.14 (β 4.214.7547.1159)
Build Date                                           Sunday, 30. August 2020
Expiration Date                                      Sunday, 22. November 2020
Install type                                         Classic

Hardware accelerated rendering (GPU)                 True
Animations                                           True
DPI                                                  96 (1,00x scale)
Language                                             en-GB

OS                                                   Windows 10 Pro x64 (10.0.19041.0) (0x30)
.NET Runtime                                         4.0.30319.42000
Physical Memory                                      32.698 MB

CPU                                                  AMD Ryzen 9 3900X 12-Core Processor            
    Speed                                            ~3800 MHz
    Cores / Threads                                  12 / 24
    Features                                         SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, AVX, AVX2

Video Card                                           Radeon RX 570 Series
    Dedicated Video RAM                              8.171 MB
    Dedicated System RAM                             0 MB
    Shared System RAM                                16.349 MB
    Vendor ID                                        0x1002
    Device ID                                        0x67DF
    Subsystem ID                                     0x353E1DA2
    Revision                                         239
    LUID                                             0x0000B30D
    Flags                                            AcgCompatible, SupportMonitoredFences, KeyedMutexConformance
    Graphics Preemption                              PrimitiveBoundary
    Compute Preemption                               DmaBufferBoundary
    Outputs                                          3
    Feature Level                                    Direct3D_12_0
    DXGI Formats                                     A8_UNorm, B8G8R8A8_UNorm, R16G16B16A16_UNorm, R16G16B16A16_Float, R32G32B32A32_Float
    Buffer Precision                                 UNorm8bpc, UNorm8bpcSrgb, UNorm16bpc, Float16bpc, Float32bpc

Video Card                                           Microsoft Basic Render Driver
    Dedicated Video RAM                              0 MB
    Dedicated System RAM                             0 MB
    Shared System RAM                                16.349 MB
    Vendor ID                                        0x1414
    Device ID                                        0x008C
    Subsystem ID                                     0x00000000
    Revision                                         0
    LUID                                             0x0000DB78
    Flags                                            Software, AcgCompatible, SupportMonitoredFences, KeyedMutexConformance
    Graphics Preemption                              InstructionBoundary
    Compute Preemption                               InstructionBoundary
    Outputs                                          0
    Feature Level                                    Direct3D_12_1
    DXGI Formats                                     A8_UNorm, B8G8R8A8_UNorm, R16G16B16A16_UNorm, R16G16B16A16_Float, R32G32B32A32_Float
    Buffer Precision                                 UNorm8bpc, UNorm8bpcSrgb, UNorm16bpc, Float16bpc, Float32bpc
```

**Comment by otuncelli** [comment] 2020-09-23 17:55
I think i've found the root cause of the issue. I'll fix this in the next release. Thanks for reporting this with detailed information.

**Comment by Eagle3386** [comment] 2020-09-23 20:56
Awesome, thanks for the quick response! 👍🏻
Regarding my report, I just thought of needed bits if it'd be my plugin, but thanks for your compliment. 😉

**Comment by otuncelli** [comment] 2020-09-30 00:02
@Eagle3386 This should be fixed in the latest version. 😉

https://github.com/otuncelli/Scalable-Vector-Graphics-Plugin-for-Paint.NET/releases/tag/v1.01

**Comment by Eagle3386** [comment] 2020-09-30 10:03
Yes, it does work now. Though, a couple of suggestions arose while testing the fixed version:
1. All labels, i. e. their font size, have increased and look, when compared to previous version's or even other Paint.NET labels, a bit weird now:
![image](https://user-images.githubusercontent.com/5111490/94671075-ad331480-0313-11eb-9530-74cb44e06e75.png)
2. Both dialog buttons received a background color - this neither fits into common Microsoft style guidelines for buttons nor the overall Paint.NET UI styling.
3. While I do get your intention of setting a background for the progress bar's text, i. e. white color behind "113 of 153", I suggest to set that transparent.
4. There seems to be a whitespace character too much in front of "153", i. e. 2 where only 1 is expected. (Yes, I'm _that_ deep into UI aesthetics... 😅)
5. While all groupboxes get disabled after launching the actual import process correctly, both, the warning icon (2nd groupbox) and the dialog's buttons, do not. I recommend disabling them while the import runs, too.

Other than that and most importantly, thanks for the quick fix - I'm finally able to work on SVG files! 🥳👏🏻👍🏻

**Comment by otuncelli** [comment] 2020-10-01 13:56
I'll consider your suggestions on the next release. Thanks for the feedback.

**Closed as completed by otuncelli** 2020-10-01 13:56 UTC
Labels: bug
